CHANGELOG.md
package.json
settings/Configuration.js
settings/TestHotkeys.js
settings/TestPlugin.js
settings/Token.js

And import `PropTypes` from `prop-types`, not `React`.

Use PropTypes, not React.PropTypes. Refs STRIPES-427

---

package.json
settings/TestPlugin.js

https://issues.folio.org/browse/STCOM-331

STCOM-331 Get Pluggable from stripes-core

---

CHANGELOG.md
package.json
settings/Configuration.js
settings/TestHotkeys.js
settings/TestPlugin.js
settings/Token.js
settings/index.js

Uses new `@folio/stripes` package.

Use stripes 1.0

---

translations/ui-developer/ca.json
translations/ui-developer/fr_FR.json
translations/ui-developer/hu.json

Update translation strings as of 20181004T193841

---

translations/ui-developer/ar.json

Update translation strings as of 20181031T224505

---

translations/ui-developer/ar.json

Update translation strings as of 20181112T151205

---

translations/ui-developer/pt_PT.json

Update translation strings as of 20181212T135930

---

translations/ui-developer/en_SE.json

Update translation strings as of 20190110T173959

---

settings/Locale.js

Add Spanish and Spanish (Latin America)

---

translations/ui-developer/es_419.json

Update translation strings as of 20190422T163602

---

package.json
settings/Configuration.js
settings/Locale.js
settings/TestHotkeys.js
settings/Token.js
settings/index.js
translations/ui-developer/en.json

Fixes [STCOR-333](https://issues.folio.org/browse/STCOR-333)

translate all the things

---

translations/ui-developer/ar.json
translations/ui-developer/ca.json
translations/ui-developer/da.json
translations/ui-developer/de.json
translations/ui-developer/en_GB.json
translations/ui-developer/en_SE.json
translations/ui-developer/en_US.json
translations/ui-developer/es.json
translations/ui-developer/es_419.json
translations/ui-developer/es_ES.json
translations/ui-developer/fr.json
translations/ui-developer/fr_FR.json
translations/ui-developer/hu.json
translations/ui-developer/it_IT.json
translations/ui-developer/pt_BR.json
translations/ui-developer/pt_PT.json
translations/ui-developer/ru.json
translations/ui-developer/zh_CN.json
translations/ui-developer/zh_TW.json

Update translation strings as of 20191022T162142

---

translations/ui-developer/ar.json
translations/ui-developer/ca.json
translations/ui-developer/da.json
translations/ui-developer/de.json
translations/ui-developer/en_GB.json
translations/ui-developer/en_SE.json
translations/ui-developer/en_US.json
translations/ui-developer/es.json
translations/ui-developer/es_419.json
translations/ui-developer/es_ES.json
translations/ui-developer/fr.json
translations/ui-developer/fr_FR.json
translations/ui-developer/hu.json
translations/ui-developer/it_IT.json
translations/ui-developer/ja.json
translations/ui-developer/pt_BR.json
translations/ui-developer/pt_PT.json
translations/ui-developer/ru.json
translations/ui-developer/zh_CN.json
translations/ui-developer/zh_TW.json

Update translation strings as of 20191101T131808

---

translations/ui-developer/ru.json

Update translation strings as of 20191111T233434

---

settings/Locale.js
translations/ui-developer/en.json

French (France) is already a translation pulled from Lokalise to GitHub; it wasn't in the locale menu.

Add French (France) to locale menu

---

translations/ui-developer/ar.json
translations/ui-developer/ca.json
translations/ui-developer/da.json
translations/ui-developer/de.json
translations/ui-developer/en_GB.json
translations/ui-developer/en_SE.json
translations/ui-developer/en_US.json
translations/ui-developer/es.json
translations/ui-developer/es_419.json
translations/ui-developer/es_ES.json
translations/ui-developer/fr.json
translations/ui-developer/fr_FR.json
translations/ui-developer/he.json
translations/ui-developer/hu.json
translations/ui-developer/it_IT.json
translations/ui-developer/ja.json
translations/ui-developer/pt_BR.json
translations/ui-developer/pt_PT.json
translations/ui-developer/ru.json
translations/ui-developer/zh_CN.json
translations/ui-developer/zh_TW.json

Update translation strings as of 20191115T154823

---

translations/ui-developer/ar.json

Update translation strings as of 20191118T154404

---

translations/ui-developer/fr_FR.json

Update translation strings as of 20191122T140350

---

translations/ui-developer/es_ES.json

Update translation strings as of 20191216T200945

---

translations/ui-developer/es.json
translations/ui-developer/es_419.json

Update translation strings as of 20191220T210632

---

translations/ui-developer/it_IT.json

Update translation strings as of 20200206T141023

---

settings/Locale.js
translations/ui-developer/en.json

I am eyeballing this without actually running the code.  Please verify syntax.

Add Urdu language

---

translations/ui-developer/ar.json
translations/ui-developer/fr_FR.json
translations/ui-developer/pt_BR.json

Update translation strings as of 20200211T224145

---

translations/ui-developer/fr_FR.json
translations/ui-developer/zh_CN.json

Update translation strings as of 20200302T163727

---

translations/ui-developer/fr_FR.json

Update translation strings as of 20200309T000645

---

package.json
settings/Configuration.js
settings/Token.js

https://issues.folio.org/browse/UID-20

UID-20 Security update eslint to >= 6.2.1 or eslint-util >= 1.4.1

---

translations/ui-developer/ar.json
translations/ui-developer/ca.json
translations/ui-developer/da.json
translations/ui-developer/de.json
translations/ui-developer/en_GB.json
translations/ui-developer/en_SE.json
translations/ui-developer/en_US.json
translations/ui-developer/es.json
translations/ui-developer/es_419.json
translations/ui-developer/es_ES.json
translations/ui-developer/fr.json
translations/ui-developer/fr_FR.json
translations/ui-developer/he.json
translations/ui-developer/hu.json
translations/ui-developer/it_IT.json
translations/ui-developer/ja.json
translations/ui-developer/pt_BR.json
translations/ui-developer/pt_PT.json
translations/ui-developer/ru.json
translations/ui-developer/ur.json
translations/ui-developer/zh_CN.json
translations/ui-developer/zh_TW.json

Update translation strings as of 20200406T162815

---

translations/ui-developer/pt_BR.json

Update translation strings as of 20200409T134057

---

translations/ui-developer/zh_TW.json

Update translation strings as of 20200505T210535

---

settings/OkapiPaths.js

comments are nice too, if you like that kind of thing.

links are nice

---

translations/ui-developer/ar.json
translations/ui-developer/ca.json
translations/ui-developer/da.json
translations/ui-developer/de.json
translations/ui-developer/en_GB.json
translations/ui-developer/en_SE.json
translations/ui-developer/en_US.json
translations/ui-developer/es.json
translations/ui-developer/es_419.json
translations/ui-developer/es_ES.json
translations/ui-developer/fr.json
translations/ui-developer/fr_FR.json
translations/ui-developer/he.json
translations/ui-developer/hu.json
translations/ui-developer/it_IT.json
translations/ui-developer/ja.json
translations/ui-developer/pt_BR.json
translations/ui-developer/pt_PT.json
translations/ui-developer/ru.json
translations/ui-developer/ur.json
translations/ui-developer/zh_CN.json
translations/ui-developer/zh_TW.json

Update translation strings as of 20200513T135229

---

translations/ui-developer/ar.json
translations/ui-developer/ca.json
translations/ui-developer/da.json
translations/ui-developer/de.json
translations/ui-developer/en_GB.json
translations/ui-developer/en_SE.json
translations/ui-developer/en_US.json
translations/ui-developer/es.json
translations/ui-developer/es_419.json
translations/ui-developer/es_ES.json
translations/ui-developer/fr.json
translations/ui-developer/fr_FR.json
translations/ui-developer/he.json
translations/ui-developer/hu.json
translations/ui-developer/it_IT.json
translations/ui-developer/ja.json
translations/ui-developer/pt_BR.json
translations/ui-developer/pt_PT.json
translations/ui-developer/ru.json
translations/ui-developer/ur.json
translations/ui-developer/zh_CN.json
translations/ui-developer/zh_TW.json

Update translation strings as of 20200515T182823

---

translations/ui-developer/ar.json
translations/ui-developer/en_GB.json
translations/ui-developer/en_SE.json
translations/ui-developer/en_US.json
translations/ui-developer/fr_FR.json
translations/ui-developer/it_IT.json
translations/ui-developer/zh_CN.json
translations/ui-developer/zh_TW.json

Update translation strings as of 20200521T190141

---

translations/ui-developer/ar.json

Update translation strings as of 20200522T132417

---

src/settings/Configuration.js
translations/ui-developer/en.json

`<Field component={Checkbox}>` does not work without this. As a result, all checkboxes were initially rendering as unchecked, even when associated with data that was set -- but no longer.

Fix react final form checkboxes

---

translations/ui-developer/ar.json
translations/ui-developer/ca.json
translations/ui-developer/da.json
translations/ui-developer/de.json
translations/ui-developer/en_GB.json
translations/ui-developer/en_SE.json
translations/ui-developer/en_US.json
translations/ui-developer/es.json
translations/ui-developer/es_419.json
translations/ui-developer/es_ES.json
translations/ui-developer/fr.json
translations/ui-developer/fr_FR.json
translations/ui-developer/he.json
translations/ui-developer/hu.json
translations/ui-developer/it_IT.json
translations/ui-developer/ja.json
translations/ui-developer/pt_BR.json
translations/ui-developer/pt_PT.json
translations/ui-developer/ru.json
translations/ui-developer/ur.json
translations/ui-developer/zh_CN.json
translations/ui-developer/zh_TW.json

Update translation strings as of 20200615T161518

---

translations/ui-developer/ru.json

Update translation strings as of 20200615T202100

---

translations/ui-developer/ar.json
translations/ui-developer/ca.json
translations/ui-developer/da.json
translations/ui-developer/de.json
translations/ui-developer/en_GB.json
translations/ui-developer/en_SE.json
translations/ui-developer/en_US.json
translations/ui-developer/es.json
translations/ui-developer/es_419.json
translations/ui-developer/es_ES.json
translations/ui-developer/fr.json
translations/ui-developer/fr_FR.json
translations/ui-developer/he.json
translations/ui-developer/hu.json
translations/ui-developer/it_IT.json
translations/ui-developer/ja.json
translations/ui-developer/pt_BR.json
translations/ui-developer/pt_PT.json
translations/ui-developer/ru.json
translations/ui-developer/ur.json
translations/ui-developer/zh_CN.json
translations/ui-developer/zh_TW.json

Update translation strings as of 20200623T182030

---

translations/ui-developer/ru.json

Update translation strings as of 20200624T182544

---

package.json
src/settings/Passwd.js
src/settings/index.js
translations/ui-developer/en.json

Provide a set-password form to allow sys-admins to directly set the password for any account.

passwd initial import

---

translations/ui-developer/ar.json
translations/ui-developer/ca.json
translations/ui-developer/da.json
translations/ui-developer/de.json
translations/ui-developer/en_GB.json
translations/ui-developer/en_SE.json
translations/ui-developer/en_US.json
translations/ui-developer/es.json
translations/ui-developer/es_419.json
translations/ui-developer/es_ES.json
translations/ui-developer/fr.json
translations/ui-developer/fr_FR.json
translations/ui-developer/he.json
translations/ui-developer/hu.json
translations/ui-developer/it_IT.json
translations/ui-developer/ja.json
translations/ui-developer/pt_BR.json
translations/ui-developer/pt_PT.json
translations/ui-developer/ru.json
translations/ui-developer/ur.json
translations/ui-developer/zh_CN.json
translations/ui-developer/zh_TW.json

Update translation strings as of 20200702T191903

---

translations/ui-developer/fr_FR.json
translations/ui-developer/pt_BR.json
translations/ui-developer/ru.json

Update translation strings as of 20200707T213422

---

CHANGELOG.md
package.json
src/settings/OkapiQuery.js
src/settings/index.js
translations/ui-developer/en.json

provide Postman/cURL-like UI to query Okapi

---

translations/ui-developer/en.json

Not sure how/why the original PR succeeded?????

including missing comma in translations

---

translations/ui-developer/ar.json
translations/ui-developer/ca.json
translations/ui-developer/da.json
translations/ui-developer/de.json
translations/ui-developer/en_GB.json
translations/ui-developer/en_SE.json
translations/ui-developer/en_US.json
translations/ui-developer/es.json
translations/ui-developer/es_419.json
translations/ui-developer/es_ES.json
translations/ui-developer/fr.json
translations/ui-developer/fr_FR.json
translations/ui-developer/he.json
translations/ui-developer/hu.json
translations/ui-developer/it_IT.json
translations/ui-developer/ja.json
translations/ui-developer/pt_BR.json
translations/ui-developer/pt_PT.json
translations/ui-developer/ru.json
translations/ui-developer/ur.json
translations/ui-developer/zh_CN.json
translations/ui-developer/zh_TW.json

Update translation strings as of 20200806T130626

---

CHANGELOG.md
src/settings/Configuration.js

Update `react-intl` to `v5`.
Refs [UID-25](https://issues.folio.org/browse/UID-25)

UID-25 react-intl v5

---

translations/ui-developer/ca.json
translations/ui-developer/da.json
translations/ui-developer/de.json
translations/ui-developer/en_GB.json
translations/ui-developer/en_US.json
translations/ui-developer/es.json
translations/ui-developer/es_419.json
translations/ui-developer/es_ES.json
translations/ui-developer/fr.json
translations/ui-developer/fr_FR.json
translations/ui-developer/he.json
translations/ui-developer/hi_IN.json
translations/ui-developer/hu.json
translations/ui-developer/it_IT.json
translations/ui-developer/ja.json
translations/ui-developer/pl.json
translations/ui-developer/pt_PT.json
translations/ui-developer/ru.json
translations/ui-developer/ur.json
translations/ui-developer/zh_TW.json

Update translation strings as of 20200928T202231

---

CHANGELOG.md
src/settings/CanIUse.js
src/settings/OkapiPaths.js

Some endpoints changed pursuant to [OKAPI-863](https://issues.folio.org/browse/OKAPI-863) / [OKAPI-835](https://issues.folio.org/browse/OKAPI-835).
Refs [UID-34](https://issues.folio.org/browse/UID-34)

UID-34 update queries with new okapi endpoints

---

translations/ui-developer/ar.json
translations/ui-developer/ca.json
translations/ui-developer/da.json
translations/ui-developer/de.json
translations/ui-developer/en_GB.json
translations/ui-developer/en_SE.json
translations/ui-developer/en_US.json
translations/ui-developer/es.json
translations/ui-developer/es_419.json
translations/ui-developer/es_ES.json
translations/ui-developer/fr.json
translations/ui-developer/fr_FR.json
translations/ui-developer/he.json
translations/ui-developer/hi_IN.json
translations/ui-developer/hu.json
translations/ui-developer/it_IT.json
translations/ui-developer/ja.json
translations/ui-developer/ko.json
translations/ui-developer/pl.json
translations/ui-developer/pt_BR.json
translations/ui-developer/pt_PT.json
translations/ui-developer/ru.json
translations/ui-developer/ur.json
translations/ui-developer/zh_CN.json
translations/ui-developer/zh_TW.json

Update translation strings as of 20201008T220807

---

translations/ui-developer/es.json
translations/ui-developer/es_419.json
translations/ui-developer/es_ES.json

Update translation strings as of 20201016T144229

---

translations/ui-developer/ja.json

Update translation strings as of 20201105T151643

---

translations/ui-developer/fr_FR.json

Update translation strings as of 20201110T192302

---

translations/ui-developer/fr_FR.json

Update translation strings as of 20201119T214636

---

CHANGELOG.md
package.json

Increment the major versions of major things.
Refs [UID-38](https://issues.folio.org/browse/UID-38), [STRIPES-721](https://issues.folio.org/browse/STRIPES-721)

UID-38 increment react-redux, redux-form, stripes

---

CHANGELOG.md
src/settings/Configuration.js
src/settings/Token.js

A component was refactored; use its replacement.
Refs [UID-72](https://issues.folio.org/browse/UID-72), [STSMACOM-490](https://issues.folio.org/browse/STSMACOM-490)

UID-72 ConfigReduxForm replaces ConfigForm

---

CHANGELOG.md
src/settings/ShowPermissions.js
translations/ui-developer/en.json

Add human-readable permission name to "Current permissions" list.

---

CHANGELOG.md
package.json
src/settings/Translations.js
src/settings/index.js
translations/ui-developer/en.json

Add page to list all currently loaded translations

---

CHANGELOG.md
package.json
src/settings/PluginSurface.js
src/settings/index.js
translations/ui-developer/en.json

Add configurable plugin-surface page

---

package.json
src/settings/StripesInspector.js
src/settings/index.js
translations/ui-developer/en.json

Deserialize and display the `stripes` object which may be usesful for
devs attempting to debug things.
Refs [UID-77](https://issues.folio.org/browse/UID-77)

UID-77 show stripes object

---

Jenkinsfile
package.json

Refs [UID-76](https://issues.folio.org/browse/UID-76)

UID-76 compile translation files to AST

---

package.json
src/settings/index.js

This was an old POC that has since been replaced by other work. Trim the
cruft!
Refs [UID-90](https://issues.folio.org/browse/UID-90), [UITEN-65](https://issues.folio.org/browse/UITEN-65)

UID-90 remote TestHotkeys

---

CHANGELOG.md
package.json

https://issues.folio.org/browse/UID-87
https://issues.folio.org/browse/UID-92
This PR removes unused/unnecessary permissions from several components and updates Stripes to its latest version.

UID-87: Remove unnecessary permissions; increment Stripes

---

src/settings/OkapiConsole/Modules.js
src/settings/OkapiConsole/OkapiConsole.css
src/settings/OkapiConsole/doc/permissions.md
src/settings/index.js
translations/ui-developer/en.json

And while I'm here, I turned on the permission requirement for the Okapi Console.

Add node information from discovery to Okapi Console

---

src/settings/OkapiConsole/Interfaces.js
src/settings/OkapiConsole/OkapiConsole.css
translations/ui-developer/en.json

* Show which modules provide each interface
* Checkbox (default off) says whether to include system interfaces
* Display total number of interfaces (accounting for the inclusion or not of system interfaces)

Okapi Console: improvements to the Interfaces tab

---

src/settings/OkapiConsole/Interfaces.js
src/settings/OkapiConsole/OkapiConsole.css
translations/ui-developer/en.json

When greater than one, show in green blob for highlighting.

Show count of providers for each interface in the OC

---

src/settings/FolioBabies.js

- Just past her first birthday, about time to add baby Evangeline!

Add Evangeline

---

CHANGELOG.md
package.json
src/settings/Configuration.js
src/settings/Token.js

Refactor forms to use final-form.
[UID-39](https://issues.folio.org/browse/UID-39)

UID-39: Refactor forms to use final-form

---

CHANGELOG.md
package.json
src/settings/index.js

Refs [UID-110](https://issues.folio.org/browse/UID-110)

UID-110 remove react-hot-loader

---

CHANGELOG.md
package.json
src/settings/StripesInspector.js

Bump react to v18, stripes to v9.
Refs [UID-131](https://issues.folio.org/browse/UID-131)

UID-131 update react to v18

---

CHANGELOG.md
src/settings/Configuration.js
translations/ui-developer/en.json

Refs [UID-140](https://issues.folio.org/browse/UID-140)

UID-140 optionally suppress react-intl warnings

---

CHANGELOG.md
package.json
src/settings/IdleSessionTimeout.js
src/settings/index.js
translations/ui-developer/en.json
translations/ui-developer/en_GB.json
translations/ui-developer/en_SE.json
translations/ui-developer/en_US.json

Provide tools to emit session-related events
Refs [UID-149](https://folio-org.atlassian.net/browse/UID-149)

UID-149 provide tools to emit session-related events

---

src/settings/ShowCapabilities.js
src/settings/index.js
translations/ui-developer/en.json

- Fulfills [UID-154](https://folio-org.atlassian.net/browse/UID-154)
- Allows user to query capabilities and capabilitySets by capability name
- [UID-156](https://folio-org.atlassian.net/browse/UID-156) will add searching by capability display name
https://github.com/folio-org/ui-developer/assets/28395235/7eeef1cc-b232-4790-acc4-f20a01e51f93

UID-154 New utility in developer settings for looking up capabilities/capabilitySets by permission name

---

CHANGELOG.md
src/settings/index.js

Refs[ UID-151](https://folio-org.atlassian.net/browse/UID-151).

UID-151: hide “I can haz endpoint?” and “Permissions inspector” if roles interface is present.

---

CHANGELOG.md
package.json

Refs [UID-186](https://folio-org.atlassian.net/browse/UID-186)

UID-186 update @folio/stripes to v10
