- package.json
- settings/Configuration.js
Old versions of react-bootstrap barf up the `Warning: Accessing PropTypes via the main React package is deprecated...` message. We could just upgrade, but are working to deprecate react-bootstrap anyway.
> don't use react-bootstrap's Row, Col. Refs STRIPES-427

- CHANGELOG.md
- package.json
The stripes-components dependency was out of sync with stripes-core,
which was causing funky overlaps of the settings pane where the third
column would be superimposed on the second. This probably means we have
our Pane and Paneset components in the wrong repository, or maybe that
we are managing that dependency incorrectly. In any case, the version of
stripes-components we get from stripes-core needs to be the same as the
one we depend on here. And now it is.
> stripes-components dep consistent with stripes-core

- package.json
- settings/Configuration.js
- settings/TestHotkeys.js
- settings/TestPlugin.js
Removes unnecessary `babel` packages and upgrades `eslint-config-stripes`.
A section of output from `yarn install`:
```
[4/5] 🔗  Linking dependencies...
warning " > @folio/stripes-components@3.0.10000507" has unmet peer dependency "@folio/stripes-core@^2.7.0".
warning "@folio/stripes-components > @folio/stripes-connect@3.2.100049" has unmet peer dependency "react@*".
warning "@folio/stripes-components > @folio/stripes-connect@3.2.100049" has unmet peer dependency "react-dom@*".
warning "@folio/stripes-components > downshift@2.2.2" has unmet peer dependency "react@>=0.14.9".
warning "@folio/stripes-components > prop-types-extra@1.1.0" has unmet peer dependency "react@>=0.14.0".
warning "@folio/stripes-components > @folio/stripes-react-hotkeys@1.0.10002" has unmet peer dependency "react@*". …
```
> Clean up dependencies

- package.json
- settings/index.js
Setup for `stripes-core` took place in https://github.com/folio-org/stripes-core/pull/431.
Turns on hot reloading for this module.
> Turn on react-hot-loader

- CHANGELOG.md
- package.json
- settings/Locale.js
- settings/index.js
Allow a user to change the locale in stripes only, without any
persistence. This will allow developers to check whether locale specific
settings and styles apply correctly; it is specifically _NOT_ intended
to be a user-facing setting to enable session-based preferences.
> support session locale

- CHANGELOG.md
- package.json
- settings/index.js
Instead of a single setting to determine visibility of settings items,
use per-item permissions.
Refs [UITEN-35](https://issues.folio.org/browse/UITEN-35)
> UITEN-35 use granular permissions

- package.json
Access to circulation settings was inadvertently removed in #60. We don't
need `settings.developer.enabled` to be a visible permission, but we do
need it to be present so that stripes-core will discover that this
module has settings.
Refs [FOLIO-2184](https://issues.folio.org/browse/FOLIO-2184)
> FOLIO-2184 restore settings

- CHANGELOG.md
- package.json
A stripes module can be more than one type, presenting an array in
`actsAs` rather than a single string to `type`.
Refs [STCOR-148](https://issues.folio.org/browse/STCOR-148)
> migrate to actsAs

- CHANGELOG.md
- package.json
The `Settings > Developer > Configuration` permission set was misnamed
and duplicated the label for the top-level `Settings > Developer`
permission.
Fixes [UID-22](https://issues.folio.org/browse/UID-22)
> UID-22 correctly label permissions

- CHANGELOG.md
- package.json
- src/settings/Configuration.js
- translations/ui-developer/en.json
Increment `stripes` to `v4.0`, `react-intl` to `v4.5`. Replace
`SafeHTMLMessage` with `FormattedMessage` and render-props to handle
links.
Refs [STRIPES-672](https://issues.folio.org/browse/STRIPES-672)
> STRIPES-672 update stripes, react-intl

- src/settings/CanIUse.js
- src/settings/index.js
Given a partial path, find the API endpoints that match it
and list the required permissions to access each. Click a
permission to retrieve the publicly accessible permission sets
that contain it.
i.e. given an endpoint, tell me what permission sets I can assign to provide access.
The UI is kinda klunky. Sorry.
> show public psets required given an endpoint

- translations/ui-developer/en.json
This made `translations/ui-developer/en.json` syntactically invalid,
and made it impossible to start Stripes on a bundle including
ui-developer.
> Remove extraneous trailing comma

- CHANGELOG.md
- src/settings/Locale.js
Use `@folio/stripes/core`'s list of supported locales instead of
maintaining a separate, local copy.
Refs [STCOR-458](https://issues.folio.org/browse/STCOR-458), [UID-28](https://issues.folio.org/browse/UID-28); replaces #162.
> UID-28 import supported locales from @folio/stripes/core

- CHANGELOG.md
- src/settings/Locale.js
A matter of days ago, FormatJS made the `type` key required on their DisplayNameOptions... while this is great for a TS codebase and all code therein can (has to) be written to conform, the outside world - including people who might be used to the browser API - are not. This was potentially done to shore up compatibility with future versions of Chrome, but who knows?
Anyways, simple enough to appease react-intl and not have the react-stack-trace-of-death.....
> Pass options object to FormatDisplayName

- src/settings/Locale.js
Don't iterate through the list of supported locales twice when once will
do just fine.
> refactor for simplicity

- translations/ui-developer/en.json
The branding guidelines [say so](https://wiki.folio.org/display/OUTREACH/FOLIO+Graphics+and+Branding+Resources?preview=%2F1410162%2F14451372%2FFOLIO_BrandIdentity_Guidelines_0318_FINAL.pdf): 
> The brand should always be in all caps when writing it out – FOLIO – since it is an acronym (the Future of Libraries is Open).
> correctly capitalize fOLiO

- package.json
Earlier PRs, #157 and #159, _claimed_ to update to `react-intl` `v5` but
didn't actually do it. I have no idea what happened there. This PR
actually makes the update!
Refs [UID-25](https://issues.folio.org/browse/UID-25)
> UID-25 actually update to react-intl v5

- CHANGELOG.md
- src/settings/CanIUse.js
- src/settings/OkapiPaths.js
Not all interfaces have a `handlers` attribute, but the previous
implementation naively assumed they did, causing an NPE.
Refs [UID-74](https://issues.folio.org/browse/UID-74)
> UID-74 recover from missing handlers attribute

- src/settings/Translations.js
When a translation file has been translated to an AST, its values will
no longer be simple strings. Naively parse these AST values back to 
strings.
Refs [UID-75](https://issues.folio.org/browse/UID-75)
> UID-75 handle AST-ified values

- CHANGELOG.md
- src/settings/index.js
You can't see things you can't spell. The permission that should guard
the stripes inspector is `developer.settings.stripesInspector`.
Refs [UID-77](https://issues.folio.org/browse/UID-77)
> UID-77 check for correctly spelled permissions

- package.json
- src/settings/HandlerSurface.js
- src/settings/PluginSurface.js
- src/settings/index.js
- translations/ui-developer/en.json
**DO NOT MERGE**
This "works", but only with whatever handler-event is named as the initial state in [the `useState` call at the top of the `HandlerSurface` functional component](https://github.com/folio-org/ui-developer/blob/b1b49fca501734a86a7c5d434b26011310025dc5/src/settings/HandlerSurface.js#L8). When you change the event name interactively, the rendering does not change with it — unlike the analogous situation with the "plugin surface" page.
I think this is because [the `<HandlerManager>` component provided by stripes-core](https://github.com/folio-org/stripes-core/blob/master/src/components/HandlerManager/HandlerManager.js) consults the `event` parameter only in the constructor, deriving the set of event-handlers at construction time and not changing them on subsequent renders.
Is …
> UID-79 Add "handler surface" page

- CHANGELOG.md
- src/settings/PluginSurface.js
- translations/ui-developer/en.json
When provided, this must be a valid JSON object. When entered into the
provided textarea, the background turns pink when the JSON is invalid,
and no data object is passed to the plugin; when the JSON is valid,
the background turns white again and the data object is passed.
Fixes UID-86.
> UID-86 Pluggable-surface page now supports optional data object

- CHANGELOG.md
- src/settings/Dependencies.js
Don't hard-code the tenant-id; extract it from `props.stripes.okapi`.
Refs [UID-88](https://issues.folio.org/browse/UID-88)
> UID-88 use dynamic tenant-id

- CHANGELOG.md
- src/settings/UserLocale.js
- translations/ui-developer/en.json
Provide a separate setting for numbering system, allowing a user to
override their locale's default setting.
Refs [UID-89](https://issues.folio.org/browse/UIID-89)
> UID-89 support numbering-system to override locale's default

- package.json
Include necessary permissions to see the okapi dependency chart.
Refs [UID-91](https://issues.folio.org/browse/UID-91)
> UID-91 include necessary permissions

- CHANGELOG.md
- src/settings/UserLocale.js
`supportedNumberingSystems` won't be exported from `@folio/stripes/core`
until `v7` so we need to define it locally here, where we are still
relying on `@folio/stripes` `v6.2`.
Refs [UID-93](https://issues.folio.org/browse/UID-93), [STRIPES-759](https://issues.folio.org/browse/STRIPES-759)
> UID-93 define `supportedNumberingSystems` locally

- CHANGELOG.md
- src/settings/PermissionsInspector.js
- translations/ui-developer/en.json
Fixes UID-99.
(Also, I fixed an alignment issue where there was some weird attempt to centre permission names when they were long enough not to fit on a single line.)
> In the Permissions Inspector, show module of origin

- src/settings/OkapiConsole/Modules.js
- translations/ui-developer/en.json
* Error callouts stay around until explicitly dismissed
* In the common case that the error being reported is a violation of
dependency constraints, the message is formatted to make the
relevant information easier to understand.
> Better error callouts when enabling/disabling modules

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
- package.json
Bump CI to active LTS NodeJS version. Remove `engines.node` from
`package.json` because node is not a production dependency (this is a
browser module only) even though we do leverage node during development
for lint, testing, and compiling translations.
Refs [UID-115](https://issues.folio.org/browse/UID-115)
> UID-115 update NodeJS to v16 in CI

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
In CI, bump NodeJS from v16 to v18.
Refs [UID-133](https://issues.folio.org/browse/UID-133)
> UID-133 use NodeJS v18 in CI builds

- CHANGELOG.md
- src/settings/Configuration.js
- translations/ui-developer/en.json
Expose the config value `preserveConsole` to allow toggling of that config value. It defaults to `false`, i.e. clear the console on logout.
Refs [UID-139](https://issues.folio.org/browse/UID-139)
> UID-139 expose config.preserveConsole

- src/settings/CanIUse.js
- src/settings/OkapiPaths.js
- src/settings/Passwd.js
Handle cookie-based authorization conservatively: provide the `x-okapi-token` HTTP request header if the token is present in `stripes`; omit it otherwise.
Refs [UID-121](https://issues.folio.org/browse/UID-121)
> UID-121 conservatively handle x-okapi-token

- CHANGELOG.md
- src/settings/CanIUse.js
- src/settings/OkapiPaths.js
- src/settings/Passwd.js
Handle cookie-based authorization conservatively: provide the
`x-okapi-token` HTTP request header if the token is present in
`stripes`; omit it otherwise.
Refs UID-121, FOLIO-3627
> UID-121 handle access-control without x-okapi-token header when possible

- src/settings/Configuration.js
Fix the typo allowing the react-intl warnings setting to be correctly displayed. The setting was, in fact, correctly handled in stripes-core but was not correctly displayed here. 
Refs [UID-153](https://folio-org.atlassian.net/browse/UID-153), [UID-147](https://folio-org.atlassian.net/browse/UID-147)
> UID-153 correctly display suppress react-intl warnings setting

- CHANGELOG.md
- package.json
- src/settings/index.js
- Ensure ShowCapabilities only displays as an option when correct interfaces are present.
- Fixes [UID-162](https://folio-org.atlassian.net/browse/UID-162)
> [UID-162] Fence off ShowCapabilities behind IfInterface checks for capabilities, capability-sets

- CHANGELOG.md
- src/settings/SessionLocale.js
- src/settings/UserLocale.js
Just like it says on the tin: sort locales by label (e.g. "Chinese (China)" or "Dutch") instead of by the locale-code (e.g. `zh-cn` or `nl`) which is not displayed
Refs [UID-107](https://folio-org.atlassian.net/issues/UID-107)
> UID-107 sort locales by label, not code

- CHANGELOG.md
- src/settings/PermissionsInspector.js
When the Permissions Inspector encounters an undefined permission (which should never happen) it now shows that permission's true name in bold red instead of crashing.
Fixes UID-183.
> Do not barf on undefined permissions

- CHANGELOG.md
- package.json
Provide `users.collection.get` in `ui-developer.settings.userLocale`. The UI form accepts a username but configuration values are stored by user-id so we need search permission to execute a query to retrieve a record by username. 
Refs [UID-126](https://folio-org.atlassian.net/browse/UID-126)
> UID-126 include missing permissions in settings.userLocale

- CHANGELOG.md
- package.json
* update react-intl
* compile translations with stripes-cli, allowing the `@formatjs/cli` dependency to be removed
Refs [UID-187](https://folio-org.atlassian.net/browse/UID-187)
> UID-187 update react-intl to v7

- .github/workflows/ui.yml
Ahem, gotta run workflows when encountering a new tag if tagging things is how you indicate a release. Whoops!
> correctly configure .github/workfows/ui.yml to publish releases

- CHANGELOG.md
- package.json
- Fulfills [UID-199](https://folio-org.atlassian.net/browse/UID-199)
- By doing this, all permission sets can be accessed in the UI if enabled individually.
> [UID-199] Add `settings.enabled` as a subpermission to all permission sets

- CHANGELOG.md
- package.json
- src/queries/index.js
- src/queries/useUsers/index.js
- src/queries/useUsers/useUsers.js
- src/settings/UserLocale.js
* The locale field has been removed, since it will be present in a new my-profile -> Language & localization settings.
* The mod-settings API is used in place of mod-configuration.
* Refactor `UserLocale` component to use a functional one.
https://github.com/folio-org/stripes-core/pull/1628
https://github.com/folio-org/ui-myprofile/pull/251
https://github.com/folio-org/ui-tenant-settings/pull/456
[UID-202](https://folio-org.atlassian.net/browse/UID-202)
> UID-202: Refactor `UserLocale` component to use mod-settings API instead of mod-configuration; remove `Locale` field.

- CHANGELOG.md
- src/settings/Dependencies.js
When sorting module descriptors, tolerate those missing the `name` attribute by supplying the `id` instead.
Refs [UID-200](https://folio-org.atlassian.net/browse/UID-200)
> UID-200 tolerate missing name when sorting modules
